# Lattice solutions come in sets

As labels rotate there must be corresponding linear functions to transform the state vectors of the nodes.  The product of all rotation matrices must be the unit-matrix.  We know the denominator terms do not change, so the middle 2 diagonals are always 1.

Lets look at some examples

In [27]:
import CollatzNDLattice.generator as gen
from functools import reduce
import numpy as np


In [23]:
def factors(n):    
    return set(reduce(list.__add__, 
                ([i, n//i] for i in range(1, int(n**0.5) + 1) if n % i == 0)))

v_factors = np.vectorize(factors)

In [10]:
## The _0111 set of four:  _0111, _1011, _1101, _1110

[
    gen.NodeRoot().forward(0).forward(1).forward(1).forward(1).vec,
    gen.NodeRoot().forward(1).forward(0).forward(1).forward(1).vec,
    gen.NodeRoot().forward(1).forward(1).forward(0).forward(1).vec,
    gen.NodeRoot().forward(1).forward(1).forward(1).forward(0).vec
]

[array([ 38, -27,  16, -54]),
 array([ 29, -27,  16, -45]),
 array([ 23, -27,  16, -39]),
 array([ 19, -27,  16, -35])]

## Note: $n + t = -16$ for all four vectors

## Lattice paths

  - \_0111, \_011, \_01, \_0, \_, \_1, \_10, \_101, \_1011
  - \_1011, \_101, \_10, \_1, \_11, \_110, \_1101
  - \_1101, \_110, \_11, \_111, \_1110
  - \_1110, \_111, \_11, \_1, \_, \_0, \_01, \_011, \_0111

In [8]:
T = np.array([[1,1.0/3,0,0],[0,1,0,0],[0,0,1,0],[0,-1.0/3,0,1]])
np.inner(T, gen.NodeRoot().forward(0).forward(1).forward(1).forward(1).vec)

array([ 29., -27.,  16., -45.])

In [9]:
T = np.array([[1,1.0/3,0,0],[0,1,0,0],[0,0,1,0],[0,-1.0/3,0,1]])
np.inner(T, gen.NodeRoot().forward(1).forward(0).forward(1).forward(1).vec)

array([ 20., -27.,  16., -36.])

In [11]:
## The _0001 set of four:  _0001, _0010, _0100, _1000

[
    gen.NodeRoot().forward(0).forward(0).forward(0).forward(1).vec,
    gen.NodeRoot().forward(0).forward(0).forward(1).forward(0).vec,
    gen.NodeRoot().forward(0).forward(1).forward(0).forward(0).vec,
    gen.NodeRoot().forward(1).forward(0).forward(0).forward(0).vec
]

[array([  8,  -3,  16, -24]),
 array([  4,  -3,  16, -20]),
 array([  2,  -3,  16, -18]),
 array([  1,  -3,  16, -17])]

## Again Note: $n + t = -16$ for all four vectors

In [15]:
## The _0011 set of four:  _0011, _0110, _1001, _1100

[
    gen.NodeRoot().forward(0).forward(0).forward(1).forward(1).vec,
    gen.NodeRoot().forward(0).forward(1).forward(1).forward(0).vec,
    gen.NodeRoot().forward(1).forward(1).forward(0).forward(0).vec,
    gen.NodeRoot().forward(1).forward(0).forward(0).forward(1).vec
]

[array([ 20,  -9,  16, -36]),
 array([ 10,  -9,  16, -26]),
 array([  5,  -9,  16, -21]),
 array([ 11,  -9,  16, -27])]

## Again Note: $n + t = -16$ for all four vectors

In [13]:
## The _000001 set of six

[
    gen.NodeRoot().forward(0).forward(0).forward(0).forward(0).forward(0).forward(1).vec,
    gen.NodeRoot().forward(0).forward(0).forward(0).forward(0).forward(1).forward(0).vec,
    gen.NodeRoot().forward(0).forward(0).forward(0).forward(1).forward(0).forward(0).vec,
    gen.NodeRoot().forward(0).forward(0).forward(1).forward(0).forward(0).forward(0).vec,
    gen.NodeRoot().forward(0).forward(1).forward(0).forward(0).forward(0).forward(0).vec,
    gen.NodeRoot().forward(1).forward(0).forward(0).forward(0).forward(0).forward(0).vec
    
]

[array([ 32,  -3,  64, -96]),
 array([ 16,  -3,  64, -80]),
 array([  8,  -3,  64, -72]),
 array([  4,  -3,  64, -68]),
 array([  2,  -3,  64, -66]),
 array([  1,  -3,  64, -65])]

In [ ]:
# Rank 7:  n+t = -64 !  And the n sequence follows the same 2^j pattern as Rank 5 _0001 set !

In [14]:
## The _000011 set of six

[
    gen.NodeRoot().forward(0).forward(0).forward(0).forward(0).forward(1).forward(1).vec,
    gen.NodeRoot().forward(0).forward(0).forward(0).forward(1).forward(1).forward(0).vec,
    gen.NodeRoot().forward(0).forward(0).forward(1).forward(1).forward(0).forward(0).vec,
    gen.NodeRoot().forward(0).forward(1).forward(1).forward(0).forward(0).forward(0).vec,
    gen.NodeRoot().forward(1).forward(1).forward(0).forward(0).forward(0).forward(0).vec,
    gen.NodeRoot().forward(1).forward(0).forward(0).forward(0).forward(0).forward(1).vec
    
]

[array([  80,   -9,   64, -144]),
 array([  40,   -9,   64, -104]),
 array([ 20,  -9,  64, -84]),
 array([ 10,  -9,  64, -74]),
 array([  5,  -9,  64, -69]),
 array([ 35,  -9,  64, -99])]

In [ ]:
# The equations within the cycles are very orderly and very much related to the bit patterns!

In [16]:
## The _111100 set of six

[
    gen.NodeRoot().forward(1).forward(1).forward(1).forward(1).forward(0).forward(0).vec,
    gen.NodeRoot().forward(1).forward(1).forward(1).forward(0).forward(0).forward(1).vec,
    gen.NodeRoot().forward(1).forward(1).forward(0).forward(0).forward(1).forward(1).vec,
    gen.NodeRoot().forward(1).forward(0).forward(0).forward(1).forward(1).forward(1).vec,
    gen.NodeRoot().forward(0).forward(0).forward(1).forward(1).forward(1).forward(1).vec,
    gen.NodeRoot().forward(0).forward(1).forward(1).forward(1).forward(1).forward(0).vec
    
]

[array([  65,  -81,   64, -129]),
 array([  89,  -81,   64, -153]),
 array([ 125,  -81,   64, -189]),
 array([ 179,  -81,   64, -243]),
 array([ 260,  -81,   64, -324]),
 array([ 130,  -81,   64, -194])]

In [28]:
v_factors(np.array([65,89,125,179,260,130]))

array([{65, 1, 13, 5}, {89, 1}, {1, 5, 125, 25}, {1, 179},
       {1, 2, 130, 260, 4, 65, 5, 10, 13, 52, 20, 26},
       {65, 1, 130, 2, 5, 10, 13, 26}], dtype=object)

In [30]:
np.array([65,89,125,179,260,130]) - 65

array([  0,  24,  60, 114, 195,  65])

In [32]:
(np.array([65,89,125,179,260,130]) - 65)/2


array([ 0. , 12. , 30. , 57. , 97.5, 32.5])

In [38]:
## The _001011 set of six

[
    gen.NodeRoot().forward(0).forward(0).forward(1).forward(0).forward(1).forward(1).vec,
    gen.NodeRoot().forward(0).forward(1).forward(0).forward(1).forward(1).forward(0).vec,
    gen.NodeRoot().forward(1).forward(0).forward(1).forward(1).forward(0).forward(0).vec,
    
    gen.NodeRoot().forward(0).forward(1).forward(1).forward(0).forward(0).forward(1).vec,
    gen.NodeRoot().forward(1).forward(1).forward(0).forward(0).forward(1).forward(0).vec,
    
    gen.NodeRoot().forward(1).forward(0).forward(0).forward(1).forward(0).forward(1).vec
    
]

[array([ 116,  -27,   64, -180]),
 array([  58,  -27,   64, -122]),
 array([ 29, -27,  64, -93]),
 array([  62,  -27,   64, -126]),
 array([ 31, -27,  64, -95]),
 array([  65,  -27,   64, -129])]

In [43]:
## The _110100 set of six

[
    gen.NodeRoot().forward(0).forward(0).forward(1).forward(1).forward(0).forward(1).vec,
    gen.NodeRoot().forward(0).forward(1).forward(1).forward(0).forward(1).forward(0).vec,
    gen.NodeRoot().forward(1).forward(1).forward(0).forward(1).forward(0).forward(0).vec,
    
    gen.NodeRoot().forward(0).forward(1).forward(0).forward(0).forward(1).forward(1).vec,
    gen.NodeRoot().forward(1).forward(0).forward(0).forward(1).forward(1).forward(0).vec,
    
    gen.NodeRoot().forward(1).forward(0).forward(1).forward(0).forward(0).forward(1).vec
    
]

[array([  92,  -27,   64, -156]),
 array([  46,  -27,   64, -110]),
 array([ 23, -27,  64, -87]),
 array([  98,  -27,   64, -162]),
 array([  49,  -27,   64, -113]),
 array([  53,  -27,   64, -117])]

In [44]:
92 - 156

-64

## So within a set we always have fractions that look like:

$ \Large{ \frac{n}{a + b}  }$

Where:

$ n = -(b + t) $

So:

$ \Large{ \frac{-(b+t)}{a + b} } $

$ a = (-3)^j $

$ b = 2^{2j} $

To get $ 1:  t \ must\  = -a - 2b $

$ t = ??? \ \ \ \ $ Is the only value that changes within a set 

### ? Big Question ?

####  Can we find a formulaic ordering of sets of size rank-1 ?

I think we can.

Then we only have to show that every set of size > 2 has at least one non-positive non-integral solution.