In [1]:
import numpy as np
import math
import sys

In [2]:
# Idx is in the range 0..2^(rank-1) - 1
def gen_matrix(rank, idx, cycle_gap):
    A = np.zeros((rank,rank))
    Y = np.zeros((rank))
    test_bit = 1
    col = 0
    for row in range(rank-3):
        if test_bit & idx == 0:
            a_val = -1.0
            y_val = 0.0
        else:
            a_val = -3.0
            y_val = 1.0
        A[row][col] = a_val
        A[row][col+1] = 2.0
        Y[row] = y_val
        #
        test_bit = test_bit << 1
        col += 1
    
    # Core matrix is last 3 rows, with cycle as last row:
    A[rank-3][rank-3] = -3.0
    A[rank-3][rank-2] = 2
    Y[rank-3] = 1.0
    
    A[rank-2][rank-2] = -1.0
    A[rank-2][rank-1] = 2
    Y[rank-2] = 0.0
    
    A[rank-1][rank-1] = 1
    A[rank-1][rank-1 - cycle_gap] = -1
    return A, Y

In [3]:
gen_matrix(3, 0, 2)

(array([[-3.,  2.,  0.],
        [ 0., -1.,  2.],
        [-1.,  0.,  1.]]),
 array([1., 0., 0.]))

In [4]:
for rank in range(3,4,1):
    for idx in range(2**(rank-3)):
        A, y = gen_matrix(rank, idx, 2)
        print(A, y, np.linalg.solve(A, y))

[[-3.  2.  0.]
 [ 0. -1.  2.]
 [-1.  0.  1.]] [1. 0. 0.] [1. 2. 1.]


In [5]:
for rank in range(4,6,1):
    for idx in range(2**(rank-1)):
        for gap in range(2, rank, 1):
            A, y = gen_matrix(rank, idx, gap)
            print(A, y, np.linalg.solve(A, y))

[[-1.  2.  0.  0.]
 [ 0. -3.  2.  0.]
 [ 0.  0. -1.  2.]
 [ 0. -1.  0.  1.]] [0. 1. 0. 0.] [2. 1. 2. 1.]
[[-1.  2.  0.  0.]
 [ 0. -3.  2.  0.]
 [ 0.  0. -1.  2.]
 [-1.  0.  0.  1.]] [0. 1. 0. 0.] [0.4 0.2 0.8 0.4]
[[-3.  2.  0.  0.]
 [ 0. -3.  2.  0.]
 [ 0.  0. -1.  2.]
 [ 0. -1.  0.  1.]] [1. 1. 0. 0.] [0.33333333 1.         2.         1.        ]
[[-3.  2.  0.  0.]
 [ 0. -3.  2.  0.]
 [ 0.  0. -1.  2.]
 [-1.  0.  0.  1.]] [1. 1. 0. 0.] [ -5.  -7. -10.  -5.]
[[-1.  2.  0.  0.]
 [ 0. -3.  2.  0.]
 [ 0.  0. -1.  2.]
 [ 0. -1.  0.  1.]] [0. 1. 0. 0.] [2. 1. 2. 1.]
[[-1.  2.  0.  0.]
 [ 0. -3.  2.  0.]
 [ 0.  0. -1.  2.]
 [-1.  0.  0.  1.]] [0. 1. 0. 0.] [0.4 0.2 0.8 0.4]
[[-3.  2.  0.  0.]
 [ 0. -3.  2.  0.]
 [ 0.  0. -1.  2.]
 [ 0. -1.  0.  1.]] [1. 1. 0. 0.] [0.33333333 1.         2.         1.        ]
[[-3.  2.  0.  0.]
 [ 0. -3.  2.  0.]
 [ 0.  0. -1.  2.]
 [-1.  0.  0.  1.]] [1. 1. 0. 0.] [ -5.  -7. -10.  -5.]
[[-1.  2.  0.  0.]
 [ 0. -3.  2.  0.]
 [ 0.  0. -1.  2.]
 [ 0. -1.  0.  

In [6]:
def float_to_fraction (x, error=0.000001):
    n = int(math.floor(x))
    x -= n
    if x < error:
        return (n, 1)
    elif 1 - error < x:
        return (n+1, 1)

    # The lower fraction is 0/1
    lower_n = 0
    lower_d = 1
    # The upper fraction is 1/1
    upper_n = 1
    upper_d = 1
    while True:
        # The middle fraction is (lower_n + upper_n) / (lower_d + upper_d)
        middle_n = lower_n + upper_n
        middle_d = lower_d + upper_d
        # If x + error < middle
        if middle_d * (x + error) < middle_n:
            # middle is our new upper
            upper_n = middle_n
            upper_d = middle_d
        # Else If middle < x - error
        elif middle_n < (x - error) * middle_d:
            # middle is our new lower
            lower_n = middle_n
            lower_d = middle_d
        # Else middle is our best fraction
        else:
            return (n * middle_d + middle_n, middle_d)
#
def floatlist_to_fraction(X, error=0.000001):
    R = []
    for x in X:
        R.append(float_to_fraction(x, error))
    return R
#

In [7]:
float_to_fraction(0.42857143)

(3, 7)

In [8]:
# 1, -5, 3/7, ...
# ===
# 2,   1, 2
# -10,   -5, -7 -10
# -23/11,   -29/11, -38/11, -19/11, -23/11

In [9]:
for rank in range(6,8,1):
    for idx in range(2**(rank-1)):
        for gap in range(2, rank, 1):
            A, y = gen_matrix(rank, idx, gap)
            print(A, y, np.linalg.solve(A, y))

[[-1.  2.  0.  0.  0.  0.]
 [ 0. -1.  2.  0.  0.  0.]
 [ 0.  0. -1.  2.  0.  0.]
 [ 0.  0.  0. -3.  2.  0.]
 [ 0.  0.  0.  0. -1.  2.]
 [ 0.  0.  0. -1.  0.  1.]] [0. 0. 0. 1. 0. 0.] [8. 4. 2. 1. 2. 1.]
[[-1.  2.  0.  0.  0.  0.]
 [ 0. -1.  2.  0.  0.  0.]
 [ 0.  0. -1.  2.  0.  0.]
 [ 0.  0.  0. -3.  2.  0.]
 [ 0.  0.  0.  0. -1.  2.]
 [ 0.  0. -1.  0.  0.  1.]] [0. 0. 0. 1. 0. 0.] [1.6 0.8 0.4 0.2 0.8 0.4]
[[-1.  2.  0.  0.  0.  0.]
 [ 0. -1.  2.  0.  0.  0.]
 [ 0.  0. -1.  2.  0.  0.]
 [ 0.  0.  0. -3.  2.  0.]
 [ 0.  0.  0.  0. -1.  2.]
 [ 0. -1.  0.  0.  0.  1.]] [0. 0. 0. 1. 0. 0.] [0.61538462 0.30769231 0.15384615 0.07692308 0.61538462 0.30769231]
[[-1.  2.  0.  0.  0.  0.]
 [ 0. -1.  2.  0.  0.  0.]
 [ 0.  0. -1.  2.  0.  0.]
 [ 0.  0.  0. -3.  2.  0.]
 [ 0.  0.  0.  0. -1.  2.]
 [-1.  0.  0.  0.  0.  1.]] [0. 0. 0. 1. 0. 0.] [0.27586207 0.13793103 0.06896552 0.03448276 0.55172414 0.27586207]
[[-3.  2.  0.  0.  0.  0.]
 [ 0. -1.  2.  0.  0.  0.]
 [ 0.  0. -1.  2.  0.  0.]
 [ 0.

 [ 0. -1.  0.  0.  0.  0.  1.]] [0. 1. 0. 1. 1. 0. 0.] [11.6  5.8  9.2  4.6  7.4 11.6  5.8]
[[-1.  2.  0.  0.  0.  0.  0.]
 [ 0. -3.  2.  0.  0.  0.  0.]
 [ 0.  0. -1.  2.  0.  0.  0.]
 [ 0.  0.  0. -3.  2.  0.  0.]
 [ 0.  0.  0.  0. -3.  2.  0.]
 [ 0.  0.  0.  0.  0. -1.  2.]
 [-1.  0.  0.  0.  0.  0.  1.]] [0. 1. 0. 1. 1. 0. 0.] [1.56756757 0.78378378 1.67567568 0.83783784 1.75675676 3.13513514
 1.56756757]
[[-3.  2.  0.  0.  0.  0.  0.]
 [ 0. -3.  2.  0.  0.  0.  0.]
 [ 0.  0. -1.  2.  0.  0.  0.]
 [ 0.  0.  0. -3.  2.  0.  0.]
 [ 0.  0.  0.  0. -3.  2.  0.]
 [ 0.  0.  0.  0.  0. -1.  2.]
 [ 0.  0.  0.  0. -1.  0.  1.]] [1. 1. 0. 1. 1. 0. 0.] [-0.25925926  0.11111111  0.66666667  0.33333333  1.          2.
  1.        ]
[[-3.  2.  0.  0.  0.  0.  0.]
 [ 0. -3.  2.  0.  0.  0.  0.]
 [ 0.  0. -1.  2.  0.  0.  0.]
 [ 0.  0.  0. -3.  2.  0.  0.]
 [ 0.  0.  0.  0. -3.  2.  0.]
 [ 0.  0.  0.  0.  0. -1.  2.]
 [ 0.  0.  0. -1.  0.  0.  1.]] [1. 1. 0. 1. 1. 0. 0.] [ -5.  -7. -10.  -5.  -7. 

 [ 0. -1.  0.  0.  0.  0.  1.]] [0. 1. 1. 1. 1. 0. 0.] [-2.65306122 -1.32653061 -1.48979592 -1.73469388 -2.10204082 -2.65306122
 -1.32653061]
[[-1.  2.  0.  0.  0.  0.  0.]
 [ 0. -3.  2.  0.  0.  0.  0.]
 [ 0.  0. -3.  2.  0.  0.  0.]
 [ 0.  0.  0. -3.  2.  0.  0.]
 [ 0.  0.  0.  0. -3.  2.  0.]
 [ 0.  0.  0.  0.  0. -1.  2.]
 [-1.  0.  0.  0.  0.  0.  1.]] [0. 1. 1. 1. 1. 0. 0.] [ -7.64705882  -3.82352941  -5.23529412  -7.35294118 -10.52941176
 -15.29411765  -7.64705882]
[[-3.  2.  0.  0.  0.  0.  0.]
 [ 0. -3.  2.  0.  0.  0.  0.]
 [ 0.  0. -3.  2.  0.  0.  0.]
 [ 0.  0.  0. -3.  2.  0.  0.]
 [ 0.  0.  0.  0. -3.  2.  0.]
 [ 0.  0.  0.  0.  0. -1.  2.]
 [ 0.  0.  0.  0. -1.  0.  1.]] [1. 1. 1. 1. 1. 0. 0.] [-0.60493827 -0.40740741 -0.11111111  0.33333333  1.          2.
  1.        ]
[[-3.  2.  0.  0.  0.  0.  0.]
 [ 0. -3.  2.  0.  0.  0.  0.]
 [ 0.  0. -3.  2.  0.  0.  0.]
 [ 0.  0.  0. -3.  2.  0.  0.]
 [ 0.  0.  0.  0. -3.  2.  0.]
 [ 0.  0.  0.  0.  0. -1.  2.]
 [ 0.  0.  0. -1.

 [ 0.  0.  0. -1.  0.  0.  1.]] [0. 1. 1. 1. 1. 0. 0.] [ -5.55555556  -2.77777778  -3.66666667  -5.          -7.
 -10.          -5.        ]
[[-1.  2.  0.  0.  0.  0.  0.]
 [ 0. -3.  2.  0.  0.  0.  0.]
 [ 0.  0. -3.  2.  0.  0.  0.]
 [ 0.  0.  0. -3.  2.  0.  0.]
 [ 0.  0.  0.  0. -3.  2.  0.]
 [ 0.  0.  0.  0.  0. -1.  2.]
 [ 0.  0. -1.  0.  0.  0.  1.]] [0. 1. 1. 1. 1. 0. 0.] [-2.96969697 -1.48484848 -1.72727273 -2.09090909 -2.63636364 -3.45454545
 -1.72727273]
[[-1.  2.  0.  0.  0.  0.  0.]
 [ 0. -3.  2.  0.  0.  0.  0.]
 [ 0.  0. -3.  2.  0.  0.  0.]
 [ 0.  0.  0. -3.  2.  0.  0.]
 [ 0.  0.  0.  0. -3.  2.  0.]
 [ 0.  0.  0.  0.  0. -1.  2.]
 [ 0. -1.  0.  0.  0.  0.  1.]] [0. 1. 1. 1. 1. 0. 0.] [-2.65306122 -1.32653061 -1.48979592 -1.73469388 -2.10204082 -2.65306122
 -1.32653061]
[[-1.  2.  0.  0.  0.  0.  0.]
 [ 0. -3.  2.  0.  0.  0.  0.]
 [ 0.  0. -3.  2.  0.  0.  0.]
 [ 0.  0.  0. -3.  2.  0.  0.]
 [ 0.  0.  0.  0. -3.  2.  0.]
 [ 0.  0.  0.  0.  0. -1.  2.]
 [-1.  0.  0.  0.

In [10]:
# -23/11, -29/11, -38/11, -19/11, -23/11

Find all 101010...1 matrices and show they all have same cycle
[[-3.  2.  0.  0.  0.  0.]
 [ 0. -1.  2.  0.  0.  0.]
 [ 0.  0. -3.  2.  0.  0.]
 [ 0.  0.  0. -1.  2.  0.]
 [ 0.  0.  0.  0. -3.  2.]
 [ 0. -1.  0.  0.  0.  1.]] [1. 0. 1. 0. 1. 0.] [1. 2. 1. 2. 1. 2.]

In [12]:
# [0.06896552 0.03448276 0.55172414 0.27586207 0.13793103 0.06896552 0.03448276]

In [13]:
for rank in range(4,8,1):
    for idx in range(2**(rank-3)):
        solns = []
        for gap in range(2, rank, 1):
            A, y = gen_matrix(rank, idx, gap)
            solns.append(floatlist_to_fraction(np.linalg.solve(A, y)))
        print(solns)

[[(2, 1), (1, 1), (2, 1), (1, 1)], [(2, 5), (1, 5), (4, 5), (2, 5)]]
[[(1, 3), (1, 1), (2, 1), (1, 1)], [(-5, 1), (-7, 1), (-10, 1), (-5, 1)]]
[[(4, 1), (2, 1), (1, 1), (2, 1), (1, 1)], [(4, 5), (2, 5), (1, 5), (4, 5), (2, 5)], [(4, 13), (2, 13), (1, 13), (8, 13), (4, 13)]]
[[(1, 1), (2, 1), (1, 1), (2, 1), (1, 1)], [(-1, 15), (2, 5), (1, 5), (4, 5), (2, 5)], [(1, 1), (2, 1), (1, 1), (2, 1), (1, 1)]]
[[(2, 3), (1, 3), (1, 1), (2, 1), (1, 1)], [(-10, 1), (-5, 1), (-7, 1), (-10, 1), (-5, 1)], [(10, 7), (5, 7), (11, 7), (20, 7), (10, 7)]]
[[(-1, 9), (1, 3), (1, 1), (2, 1), (1, 1)], [(-11, 3), (-5, 1), (-7, 1), (-10, 1), (-5, 1)], [(-19, 11), (-23, 11), (-29, 11), (-38, 11), (-19, 11)]]
[[(8, 1), (4, 1), (2, 1), (1, 1), (2, 1), (1, 1)], [(8, 5), (4, 5), (2, 5), (1, 5), (4, 5), (2, 5)], [(8, 13), (4, 13), (2, 13), (1, 13), (8, 13), (4, 13)], [(8, 29), (4, 29), (2, 29), (1, 29), (16, 29), (8, 29)]]
[[(7, 3), (4, 1), (2, 1), (1, 1), (2, 1), (1, 1)], [(1, 5), (4, 5), (2, 5), (1, 5), (4, 5), (2

In [14]:
A, y = gen_matrix(4, 0, 3)
floatlist_to_fraction(np.linalg.solve(A, y))

[(2, 5), (1, 5), (4, 5), (2, 5)]

In [15]:
A, y = gen_matrix(4, 1, 3)
floatlist_to_fraction(np.linalg.solve(A, y))

[(-5, 1), (-7, 1), (-10, 1), (-5, 1)]

In [16]:
A

array([[-3.,  2.,  0.,  0.],
       [ 0., -3.,  2.,  0.],
       [ 0.,  0., -1.,  2.],
       [-1.,  0.,  0.,  1.]])

In [17]:
A, y = gen_matrix(5, 0, 3)
floatlist_to_fraction(np.linalg.solve(A, y))

[(4, 5), (2, 5), (1, 5), (4, 5), (2, 5)]

In [18]:
A, y = gen_matrix(5, 1, 3)
floatlist_to_fraction(np.linalg.solve(A, y))

[(-1, 15), (2, 5), (1, 5), (4, 5), (2, 5)]

In [27]:
A, y = gen_matrix(5, 2, 3)
floatlist_to_fraction(np.linalg.solve(A, y))

[(-10, 1), (-5, 1), (-7, 1), (-10, 1), (-5, 1)]

In [28]:
A

array([[-1.,  2.,  0.,  0.,  0.],
       [ 0., -3.,  2.,  0.,  0.],
       [ 0.,  0., -3.,  2.,  0.],
       [ 0.,  0.,  0., -1.,  2.],
       [ 0., -1.,  0.,  0.,  1.]])

In [20]:
A, y = gen_matrix(5, 3, 3)
floatlist_to_fraction(np.linalg.solve(A, y))

[(-11, 3), (-5, 1), (-7, 1), (-10, 1), (-5, 1)]

In [21]:
A, y = gen_matrix(6, 7, 3)
floatlist_to_fraction(np.linalg.solve(A, y))

[(-25, 9), (-11, 3), (-5, 1), (-7, 1), (-10, 1), (-5, 1)]

In [22]:
A, y = gen_matrix(7, 15, 3)
floatlist_to_fraction(np.linalg.solve(A, y))

[(-59, 27), (-25, 9), (-11, 3), (-5, 1), (-7, 1), (-10, 1), (-5, 1)]

In [23]:
A, y = gen_matrix(8, 31, 3)
floatlist_to_fraction(np.linalg.solve(A, y))

[(-145, 81),
 (-59, 27),
 (-25, 9),
 (-11, 3),
 (-5, 1),
 (-7, 1),
 (-10, 1),
 (-5, 1)]

In [24]:
145*9

1305

In [25]:
A, y = gen_matrix(9, 63, 3)
floatlist_to_fraction(np.linalg.solve(A, y))

[(-371, 243),
 (-145, 81),
 (-59, 27),
 (-25, 9),
 (-11, 3),
 (-5, 1),
 (-7, 1),
 (-10, 1),
 (-5, 1)]

In [26]:
371*9

3339