In [1]:
import numpy as np
from fractions import Fraction

# 1. Introduction

We start by introducing a simple recursively generatable infinite series of linear equations that embody the Collatz sequences.  From these generated matrices, we identify a generator for the solutions and recognize a pattern by representing the solutions values in the form $\frac{2^n\ -\ c}{3^m}$.  All integers have infinitely many representations of this form, but a restricted legal set of parameters falls out of the sequence of linear equations.


# 2. The Linear Equations

## 2.1 Generation 0

We start with 1 matrix

$$
\begin{bmatrix} 
    -3 & 2 & 0 \\
    0 & -1 & 2 \\ 
    -1 & 0 & 1 
\end{bmatrix}
X
=
\begin{bmatrix} 
    1 \\
    0 \\ 
    0 
\end{bmatrix}
$$

$$\implies$$

$$
X
=
\begin{bmatrix} 
    1 \\
    2 \\ 
    1 
\end{bmatrix}
$$


In [2]:
A = np.array([
    [-3,2,0],
    [0,-1,2],
    [-1,0, 1],
])
b = np.array([1,0,0])
x = np.linalg.solve(A,b)
x

array([1., 2., 1.])

## 2.2 Generation 1

We generate 2 matrices, keeping the Generation 0 equations as a kernel and we add two different rows above it, one for each of the $\frac{3o+1}{2}$ and $\frac{e}{2}$ cases

$$
\begin{bmatrix} 
    -1 & 2 & 0 & 0\\
    0 & \textbf{-3} & \textbf{2} & \textbf{0}\\ 
    0 & \textbf{0} & \textbf{-1} & \textbf{2}\\
    0 & \textbf{-1} & \textbf{0} & \textbf{1} 
\end{bmatrix}
X
=
\begin{bmatrix} 
    0 \\
    \textbf{1} \\ 
    \textbf{0} \\ 
    \textbf{0} 
\end{bmatrix}
$$

$$\implies$$

$$
X
=
\begin{bmatrix} 
    2 \\
    \textbf{1} \\ 
    \textbf{2} \\ 
    \textbf{1}
\end{bmatrix}
$$

$$
\begin{bmatrix} 
    -3 & 2 & 0 & 0\\
    0 & \textbf{-3} & \textbf{2} & \textbf{0}\\ 
    0 & \textbf{0} & \textbf{-1} & \textbf{2}\\
    0 & \textbf{-1} & \textbf{0} & \textbf{1} 
\end{bmatrix}
X
=
\begin{bmatrix} 
    1 \\
    \textbf{1} \\ 
    \textbf{0} \\ 
    \textbf{0} 
\end{bmatrix}
$$

$$\implies$$

$$
X
=
\begin{bmatrix} 
    \frac{1}{3} \\
    \textbf{1} \\
    \textbf{2} \\ 
    \textbf{1} \\ 
\end{bmatrix}
$$


In [3]:
A = np.array([
    [-1,2,0,0],
    [0,-3,2,0],
    [0,0,-1,2],
    [0,-1,0, 1],
])
b = np.array([0,1,0,0])
x = np.linalg.solve(A,b)
x

array([2., 1., 2., 1.])

In [4]:
A = np.array([
    [-3,2,0,0],
    [0,-3,2,0],
    [0,0,-1,2],
    [0,-1,0, 1],
])
b = np.array([1,1,0,0])
x = np.linalg.solve(A,b)
x

array([0.33333333, 1.        , 2.        , 1.        ])

## 2.3 Generation 2

Each generation 1 matrix becomes 2 matrices, by adding pair of rows to the matrices from the previous generation for each of the  $\frac{3o+1}{2}$ and $\frac{e}{2}$ cases

  - 1
$$
\begin{bmatrix} 
    -1 & 2 & 0 & 0 & 0\\
    0 & -1 & 2 & 0 & 0\\
    0 & 0 & \textbf{-3} & \textbf{2} & \textbf{0}\\ 
    0 & 0 & \textbf{0} & \textbf{-1} & \textbf{2}\\
    0 & 0 & \textbf{-1} & \textbf{0} & \textbf{1} 
\end{bmatrix}
X
=
\begin{bmatrix} 
    0 \\
    0 \\
    \textbf{1} \\ 
    \textbf{0} \\ 
    \textbf{0} 
\end{bmatrix}
$$

$$\implies$$

$$
X
=
\begin{bmatrix} 
    4 \\
    2 \\
    \textbf{1} \\ 
    \textbf{2} \\ 
    \textbf{1}
\end{bmatrix}
$$

  - 2

$$
\begin{bmatrix} 
    -3 & 2 & 0 & 0 & 0\\
    0 & -1 & 2 & 0 & 0\\
    0 & 0 & \textbf{-3} & \textbf{2} & \textbf{0}\\ 
    0 & 0 & \textbf{0} & \textbf{-1} & \textbf{2}\\
    0 & 0 & \textbf{-1} & \textbf{0} & \textbf{1} 
\end{bmatrix}
X
=
\begin{bmatrix} 
    1 \\
    0 \\
    \textbf{1} \\ 
    \textbf{0} \\ 
    \textbf{0} 
\end{bmatrix}
$$

$$\implies$$

$$
X
=
\begin{bmatrix} 
    \frac{2}{3} \\
    1 \\
    \textbf{1} \\ 
    \textbf{2} \\ 
    \textbf{1}
\end{bmatrix}
$$

  - 3

$$
\begin{bmatrix} 
    -1 & 2 & 0 & 0 & 0\\
    0 & -3 & 2 & 0 & 0\\
    0 & 0 & \textbf{-3} & \textbf{2} & \textbf{0}\\ 
    0 & 0 & \textbf{0} & \textbf{-1} & \textbf{2}\\
    0 & 0 & \textbf{-1} & \textbf{0} & \textbf{1} 
\end{bmatrix}
X
=
\begin{bmatrix} 
    0 \\
    1 \\
    \textbf{1} \\ 
    \textbf{0} \\ 
    \textbf{0} 
\end{bmatrix}
$$

$$\implies$$

$$
X
=
\begin{bmatrix} 
    \frac{2}{3} \\
    \frac{1}{3} \\
    \textbf{1} \\ 
    \textbf{2} \\ 
    \textbf{1}
\end{bmatrix}
$$

  - 4

$$
\begin{bmatrix} 
    -3 & 2 & 0 & 0 & 0\\
    0 & -3 & 2 & 0 & 0\\
    0 & 0 & \textbf{-3} & \textbf{2} & \textbf{0}\\ 
    0 & 0 & \textbf{0} & \textbf{-1} & \textbf{2}\\
    0 & 0 & \textbf{-1} & \textbf{0} & \textbf{1} 
\end{bmatrix}
X
=
\begin{bmatrix} 
    1 \\
    1 \\
    \textbf{1} \\ 
    \textbf{0} \\ 
    \textbf{0} 
\end{bmatrix}
$$

$$\implies$$

$$
X
=
\begin{bmatrix} 
    \frac{-1}{9} \\
    \frac{1}{3} \\
    \textbf{1} \\ 
    \textbf{2} \\ 
    \textbf{1}
\end{bmatrix}
$$



In [5]:
A = np.array([
    [-1,2,0,0,0],
    [0,-1,2,0,0],
    [0,0,-3,2,0],
    [0,0,0,-1,2],
    [0,0,-1,0, 1],
])
b = np.array([0,0,1,0,0])
x = np.linalg.solve(A,b)
x

array([4., 2., 1., 2., 1.])

In [6]:
A = np.array([
    [-3,2,0,0,0],
    [0,-1,2,0,0],
    [0,0,-3,2,0],
    [0,0,0,-1,2],
    [0,0,-1,0, 1],
])
b = np.array([0,1,1,0,0])
x = np.linalg.solve(A,b)
x

array([0.66666667, 1.        , 1.        , 2.        , 1.        ])

In [7]:
A = np.array([
    [-1,2,0,0,0],
    [0,-3,2,0,0],
    [0,0,-3,2,0],
    [0,0,0,-1,2],
    [0,0,-1,0, 1],
])
b = np.array([1,0,1,0,0])
x = np.linalg.solve(A,b)
x

array([0.33333333, 0.66666667, 1.        , 2.        , 1.        ])

In [8]:
A = np.array([
    [-3,2,0,0,0],
    [0,-3,2,0,0],
    [0,0,-3,2,0],
    [0,0,0,-1,2],
    [0,0,-1,0, 1],
])
b = np.array([1,1,1,0,0])
x = np.linalg.solve(A,b)
x

array([-0.11111111,  0.33333333,  1.        ,  2.        ,  1.        ])

## 2.4 Generation N Matrices

We have $2^N$ matrices for the Nth generation built from the (N-1)th generation:


$$
\begin{bmatrix} 
    -1\ or\ -3 & 2 & \dots & 0 & 0\\
    0 & \vdots & \ddots  & 0 & 0\\
    0 & 0 & \textbf{-3} & \textbf{2} & \textbf{0}\\ 
    0 & 0 & \textbf{0} & \textbf{-1} & \textbf{2}\\
    0 & 0 & \textbf{-1} & \textbf{0} & \textbf{1} 
\end{bmatrix}
X
=
\begin{bmatrix} 
    0\ or\ 1\\
    0 \\
    \textbf{1} \\ 
    \textbf{0} \\ 
    \textbf{0} 
\end{bmatrix}
$$


## 2.5 Integer Solutions are Collatz Sequences

When $X[0]$ is an integer, the solutions of these equations are Collatz sequences by design.  

### 2.5.1 Straight forward pattern to $X[0]$ solutions

If we write each $X_n[0]$ as $\frac{2^n - c}{3^m}$

The we find there are always two $X_{(n+1)e,o}[0]$ in the next generation:

  - $X_{(n+1)e}[0] = \frac{2^{(n+1)} - c}{3^m} $
  - $X_{(n+1)o}[0] = \frac{2^{(n+1)} - (3c + 2^n)}{3^{(m+1)}} $

### 2.5.2 The first 8 generations of $X[0]$ solution values:

In this code we represent the $\frac{2^n - c}{3^m}$ form of the integers with the tuple $(n,m.c)$ and only reduce this form when checking for integer solutions.


In [9]:
def tupArrayToLatex(A):
    latex = ["$$\\begin{Bmatrix}"]
    for tup in A:
        n,m,c = tup
        f = Fraction(2**n -c, 3**m)
        if f.denominator == 1:
            latex.append("\\frac{2^%d\\ -%d}{3^%d}\\mathbf{=\ %d}\\\\"%(n, c, m, f.numerator))
        else:
            latex.append("\\frac{2^%d\\ -%d}{3^%d}=\\frac{%d}{%d}\\\\"%(n, c, m, f.numerator, f.denominator))
    latex.append("\\end{Bmatrix}$$")
    return "\n".join(latex)
#
def nextTups(tups):
    head = []
    tail = []
    for tup in tups:
        p2, p3, c = tup
        t1 = (p2 + 1, p3, c)
        t2 = (p2 + 1, p3 + 1, c*3 + 2**p2)
        head.append(t1)
        tail.append(t2)
    return head+tail
#
def genLatexGenerations(N):
    tups = [(0,0,0)]
    for i in range(N):
        print("  - %d\n"%(i))
        print(tupArrayToLatex(tups))
        print("\n")
        tups = nextTups(tups)
#

In [10]:
genLatexGenerations(8)

# Note: Generation 7 is right on the edge of what MathJax can handle.  One more space per-line == DEATH

  - 0

$$\begin{Bmatrix}
\frac{2^0\ -0}{3^0}\mathbf{=\ 1}\\
\end{Bmatrix}$$


  - 1

$$\begin{Bmatrix}
\frac{2^1\ -0}{3^0}\mathbf{=\ 2}\\
\frac{2^1\ -1}{3^1}=\frac{1}{3}\\
\end{Bmatrix}$$


  - 2

$$\begin{Bmatrix}
\frac{2^2\ -0}{3^0}\mathbf{=\ 4}\\
\frac{2^2\ -1}{3^1}\mathbf{=\ 1}\\
\frac{2^2\ -2}{3^1}=\frac{2}{3}\\
\frac{2^2\ -5}{3^2}=\frac{-1}{9}\\
\end{Bmatrix}$$


  - 3

$$\begin{Bmatrix}
\frac{2^3\ -0}{3^0}\mathbf{=\ 8}\\
\frac{2^3\ -1}{3^1}=\frac{7}{3}\\
\frac{2^3\ -2}{3^1}\mathbf{=\ 2}\\
\frac{2^3\ -5}{3^2}=\frac{1}{3}\\
\frac{2^3\ -4}{3^1}=\frac{4}{3}\\
\frac{2^3\ -7}{3^2}=\frac{1}{9}\\
\frac{2^3\ -10}{3^2}=\frac{-2}{9}\\
\frac{2^3\ -19}{3^3}=\frac{-11}{27}\\
\end{Bmatrix}$$


  - 4

$$\begin{Bmatrix}
\frac{2^4\ -0}{3^0}\mathbf{=\ 16}\\
\frac{2^4\ -1}{3^1}\mathbf{=\ 5}\\
\frac{2^4\ -2}{3^1}=\frac{14}{3}\\
\frac{2^4\ -5}{3^2}=\frac{11}{9}\\
\frac{2^4\ -4}{3^1}\mathbf{=\ 4}\\
\frac{2^4\ -7}{3^2}\mathbf{=\ 1}\\
\frac{2^4\ -10}{3^2}=\frac{2}{3}\\
\frac{2^4\ -19}{3^3}=\frac{-1}{9}\

$$\begin{Bmatrix}
\frac{2^0\ -0}{3^0}\mathbf{=\ 1}\\
\end{Bmatrix}$$


  - 1

$$\begin{Bmatrix}
\frac{2^1\ -0}{3^0}\mathbf{=\ 2}\\
\frac{2^1\ -1}{3^1}=\frac{1}{3}\\
\end{Bmatrix}$$


  - 2

$$\begin{Bmatrix}
\frac{2^2\ -0}{3^0}\mathbf{=\ 4}\\
\frac{2^2\ -1}{3^1}\mathbf{=\ 1}\\
\frac{2^2\ -2}{3^1}=\frac{2}{3}\\
\frac{2^2\ -5}{3^2}=\frac{-1}{9}\\
\end{Bmatrix}$$


  - 3

$$\begin{Bmatrix}
\frac{2^3\ -0}{3^0}\mathbf{=\ 8}\\
\frac{2^3\ -1}{3^1}=\frac{7}{3}\\
\frac{2^3\ -2}{3^1}\mathbf{=\ 2}\\
\frac{2^3\ -5}{3^2}=\frac{1}{3}\\
\frac{2^3\ -4}{3^1}=\frac{4}{3}\\
\frac{2^3\ -7}{3^2}=\frac{1}{9}\\
\frac{2^3\ -10}{3^2}=\frac{-2}{9}\\
\frac{2^3\ -19}{3^3}=\frac{-11}{27}\\
\end{Bmatrix}$$


  - 4

$$\begin{Bmatrix}
\frac{2^4\ -0}{3^0}\mathbf{=\ 16}\\
\frac{2^4\ -1}{3^1}\mathbf{=\ 5}\\
\frac{2^4\ -2}{3^1}=\frac{14}{3}\\
\frac{2^4\ -5}{3^2}=\frac{11}{9}\\
\frac{2^4\ -4}{3^1}\mathbf{=\ 4}\\
\frac{2^4\ -7}{3^2}\mathbf{=\ 1}\\
\frac{2^4\ -10}{3^2}=\frac{2}{3}\\
\frac{2^4\ -19}{3^3}=\frac{-1}{9}\\
\frac{2^4\ -8}{3^1}=\frac{8}{3}\\
\frac{2^4\ -11}{3^2}=\frac{5}{9}\\
\frac{2^4\ -14}{3^2}=\frac{2}{9}\\
\frac{2^4\ -23}{3^3}=\frac{-7}{27}\\
\frac{2^4\ -20}{3^2}=\frac{-4}{9}\\
\frac{2^4\ -29}{3^3}=\frac{-13}{27}\\
\frac{2^4\ -38}{3^3}=\frac{-22}{27}\\
\frac{2^4\ -65}{3^4}=\frac{-49}{81}\\
\end{Bmatrix}$$


  - 5

$$\begin{Bmatrix}
\frac{2^5\ -0}{3^0}\mathbf{=\ 32}\\
\frac{2^5\ -1}{3^1}=\frac{31}{3}\\
\frac{2^5\ -2}{3^1}\mathbf{=\ 10}\\
\frac{2^5\ -5}{3^2}\mathbf{=\ 3}\\
\frac{2^5\ -4}{3^1}=\frac{28}{3}\\
\frac{2^5\ -7}{3^2}=\frac{25}{9}\\
\frac{2^5\ -10}{3^2}=\frac{22}{9}\\
\frac{2^5\ -19}{3^3}=\frac{13}{27}\\
\frac{2^5\ -8}{3^1}\mathbf{=\ 8}\\
\frac{2^5\ -11}{3^2}=\frac{7}{3}\\
\frac{2^5\ -14}{3^2}\mathbf{=\ 2}\\
\frac{2^5\ -23}{3^3}=\frac{1}{3}\\
\frac{2^5\ -20}{3^2}=\frac{4}{3}\\
\frac{2^5\ -29}{3^3}=\frac{1}{9}\\
\frac{2^5\ -38}{3^3}=\frac{-2}{9}\\
\frac{2^5\ -65}{3^4}=\frac{-11}{27}\\
\frac{2^5\ -16}{3^1}=\frac{16}{3}\\
\frac{2^5\ -19}{3^2}=\frac{13}{9}\\
\frac{2^5\ -22}{3^2}=\frac{10}{9}\\
\frac{2^5\ -31}{3^3}=\frac{1}{27}\\
\frac{2^5\ -28}{3^2}=\frac{4}{9}\\
\frac{2^5\ -37}{3^3}=\frac{-5}{27}\\
\frac{2^5\ -46}{3^3}=\frac{-14}{27}\\
\frac{2^5\ -73}{3^4}=\frac{-41}{81}\\
\frac{2^5\ -40}{3^2}=\frac{-8}{9}\\
\frac{2^5\ -49}{3^3}=\frac{-17}{27}\\
\frac{2^5\ -58}{3^3}=\frac{-26}{27}\\
\frac{2^5\ -85}{3^4}=\frac{-53}{81}\\
\frac{2^5\ -76}{3^3}=\frac{-44}{27}\\
\frac{2^5\ -103}{3^4}=\frac{-71}{81}\\
\frac{2^5\ -130}{3^4}=\frac{-98}{81}\\
\frac{2^5\ -211}{3^5}=\frac{-179}{243}\\
\end{Bmatrix}$$


  - 6

$$\begin{Bmatrix}
\frac{2^6\ -0}{3^0}\mathbf{=\ 64}\\
\frac{2^6\ -1}{3^1}\mathbf{=\ 21}\\
\frac{2^6\ -2}{3^1}=\frac{62}{3}\\
\frac{2^6\ -5}{3^2}=\frac{59}{9}\\
\frac{2^6\ -4}{3^1}\mathbf{=\ 20}\\
\frac{2^6\ -7}{3^2}=\frac{19}{3}\\
\frac{2^6\ -10}{3^2}\mathbf{=\ 6}\\
\frac{2^6\ -19}{3^3}=\frac{5}{3}\\
\frac{2^6\ -8}{3^1}=\frac{56}{3}\\
\frac{2^6\ -11}{3^2}=\frac{53}{9}\\
\frac{2^6\ -14}{3^2}=\frac{50}{9}\\
\frac{2^6\ -23}{3^3}=\frac{41}{27}\\
\frac{2^6\ -20}{3^2}=\frac{44}{9}\\
\frac{2^6\ -29}{3^3}=\frac{35}{27}\\
\frac{2^6\ -38}{3^3}=\frac{26}{27}\\
\frac{2^6\ -65}{3^4}=\frac{-1}{81}\\
\frac{2^6\ -16}{3^1}\mathbf{=\ 16}\\
\frac{2^6\ -19}{3^2}\mathbf{=\ 5}\\
\frac{2^6\ -22}{3^2}=\frac{14}{3}\\
\frac{2^6\ -31}{3^3}=\frac{11}{9}\\
\frac{2^6\ -28}{3^2}\mathbf{=\ 4}\\
\frac{2^6\ -37}{3^3}\mathbf{=\ 1}\\
\frac{2^6\ -46}{3^3}=\frac{2}{3}\\
\frac{2^6\ -73}{3^4}=\frac{-1}{9}\\
\frac{2^6\ -40}{3^2}=\frac{8}{3}\\
\frac{2^6\ -49}{3^3}=\frac{5}{9}\\
\frac{2^6\ -58}{3^3}=\frac{2}{9}\\
\frac{2^6\ -85}{3^4}=\frac{-7}{27}\\
\frac{2^6\ -76}{3^3}=\frac{-4}{9}\\
\frac{2^6\ -103}{3^4}=\frac{-13}{27}\\
\frac{2^6\ -130}{3^4}=\frac{-22}{27}\\
\frac{2^6\ -211}{3^5}=\frac{-49}{81}\\
\frac{2^6\ -32}{3^1}=\frac{32}{3}\\
\frac{2^6\ -35}{3^2}=\frac{29}{9}\\
\frac{2^6\ -38}{3^2}=\frac{26}{9}\\
\frac{2^6\ -47}{3^3}=\frac{17}{27}\\
\frac{2^6\ -44}{3^2}=\frac{20}{9}\\
\frac{2^6\ -53}{3^3}=\frac{11}{27}\\
\frac{2^6\ -62}{3^3}=\frac{2}{27}\\
\frac{2^6\ -89}{3^4}=\frac{-25}{81}\\
\frac{2^6\ -56}{3^2}=\frac{8}{9}\\
\frac{2^6\ -65}{3^3}=\frac{-1}{27}\\
\frac{2^6\ -74}{3^3}=\frac{-10}{27}\\
\frac{2^6\ -101}{3^4}=\frac{-37}{81}\\
\frac{2^6\ -92}{3^3}=\frac{-28}{27}\\
\frac{2^6\ -119}{3^4}=\frac{-55}{81}\\
\frac{2^6\ -146}{3^4}=\frac{-82}{81}\\
\frac{2^6\ -227}{3^5}=\frac{-163}{243}\\
\frac{2^6\ -80}{3^2}=\frac{-16}{9}\\
\frac{2^6\ -89}{3^3}=\frac{-25}{27}\\
\frac{2^6\ -98}{3^3}=\frac{-34}{27}\\
\frac{2^6\ -125}{3^4}=\frac{-61}{81}\\
\frac{2^6\ -116}{3^3}=\frac{-52}{27}\\
\frac{2^6\ -143}{3^4}=\frac{-79}{81}\\
\frac{2^6\ -170}{3^4}=\frac{-106}{81}\\
\frac{2^6\ -251}{3^5}=\frac{-187}{243}\\
\frac{2^6\ -152}{3^3}=\frac{-88}{27}\\
\frac{2^6\ -179}{3^4}=\frac{-115}{81}\\
\frac{2^6\ -206}{3^4}=\frac{-142}{81}\\
\frac{2^6\ -287}{3^5}=\frac{-223}{243}\\
\frac{2^6\ -260}{3^4}=\frac{-196}{81}\\
\frac{2^6\ -341}{3^5}=\frac{-277}{243}\\
\frac{2^6\ -422}{3^5}=\frac{-358}{243}\\
\frac{2^6\ -665}{3^6}=\frac{-601}{729}\\
\end{Bmatrix}$$


  - 7

$$\begin{Bmatrix}
\frac{2^7\ -0}{3^0}\mathbf{=\ 128}\\
\frac{2^7\ -1}{3^1}=\frac{127}{3}\\
\frac{2^7\ -2}{3^1}\mathbf{=\ 42}\\
\frac{2^7\ -5}{3^2}=\frac{41}{3}\\
\frac{2^7\ -4}{3^1}=\frac{124}{3}\\
\frac{2^7\ -7}{3^2}=\frac{121}{9}\\
\frac{2^7\ -10}{3^2}=\frac{118}{9}\\
\frac{2^7\ -19}{3^3}=\frac{109}{27}\\
\frac{2^7\ -8}{3^1}\mathbf{=\ 40}\\
\frac{2^7\ -11}{3^2}\mathbf{=\ 13}\\
\frac{2^7\ -14}{3^2}=\frac{38}{3}\\
\frac{2^7\ -23}{3^3}=\frac{35}{9}\\
\frac{2^7\ -20}{3^2}\mathbf{=\ 12}\\
\frac{2^7\ -29}{3^3}=\frac{11}{3}\\
\frac{2^7\ -38}{3^3}=\frac{10}{3}\\
\frac{2^7\ -65}{3^4}=\frac{7}{9}\\
\frac{2^7\ -16}{3^1}=\frac{112}{3}\\
\frac{2^7\ -19}{3^2}=\frac{109}{9}\\
\frac{2^7\ -22}{3^2}=\frac{106}{9}\\
\frac{2^7\ -31}{3^3}=\frac{97}{27}\\
\frac{2^7\ -28}{3^2}=\frac{100}{9}\\
\frac{2^7\ -37}{3^3}=\frac{91}{27}\\
\frac{2^7\ -46}{3^3}=\frac{82}{27}\\
\frac{2^7\ -73}{3^4}=\frac{55}{81}\\
\frac{2^7\ -40}{3^2}=\frac{88}{9}\\
\frac{2^7\ -49}{3^3}=\frac{79}{27}\\
\frac{2^7\ -58}{3^3}=\frac{70}{27}\\
\frac{2^7\ -85}{3^4}=\frac{43}{81}\\
\frac{2^7\ -76}{3^3}=\frac{52}{27}\\
\frac{2^7\ -103}{3^4}=\frac{25}{81}\\
\frac{2^7\ -130}{3^4}=\frac{-2}{81}\\
\frac{2^7\ -211}{3^5}=\frac{-83}{243}\\
\frac{2^7\ -32}{3^1}\mathbf{=\ 32}\\
\frac{2^7\ -35}{3^2}=\frac{31}{3}\\
\frac{2^7\ -38}{3^2}\mathbf{=\ 10}\\
\frac{2^7\ -47}{3^3}\mathbf{=\ 3}\\
\frac{2^7\ -44}{3^2}=\frac{28}{3}\\
\frac{2^7\ -53}{3^3}=\frac{25}{9}\\
\frac{2^7\ -62}{3^3}=\frac{22}{9}\\
\frac{2^7\ -89}{3^4}=\frac{13}{27}\\
\frac{2^7\ -56}{3^2}\mathbf{=\ 8}\\
\frac{2^7\ -65}{3^3}=\frac{7}{3}\\
\frac{2^7\ -74}{3^3}\mathbf{=\ 2}\\
\frac{2^7\ -101}{3^4}=\frac{1}{3}\\
\frac{2^7\ -92}{3^3}=\frac{4}{3}\\
\frac{2^7\ -119}{3^4}=\frac{1}{9}\\
\frac{2^7\ -146}{3^4}=\frac{-2}{9}\\
\frac{2^7\ -227}{3^5}=\frac{-11}{27}\\
\frac{2^7\ -80}{3^2}=\frac{16}{3}\\
\frac{2^7\ -89}{3^3}=\frac{13}{9}\\
\frac{2^7\ -98}{3^3}=\frac{10}{9}\\
\frac{2^7\ -125}{3^4}=\frac{1}{27}\\
\frac{2^7\ -116}{3^3}=\frac{4}{9}\\
\frac{2^7\ -143}{3^4}=\frac{-5}{27}\\
\frac{2^7\ -170}{3^4}=\frac{-14}{27}\\
\frac{2^7\ -251}{3^5}=\frac{-41}{81}\\
\frac{2^7\ -152}{3^3}=\frac{-8}{9}\\
\frac{2^7\ -179}{3^4}=\frac{-17}{27}\\
\frac{2^7\ -206}{3^4}=\frac{-26}{27}\\
\frac{2^7\ -287}{3^5}=\frac{-53}{81}\\
\frac{2^7\ -260}{3^4}=\frac{-44}{27}\\
\frac{2^7\ -341}{3^5}=\frac{-71}{81}\\
\frac{2^7\ -422}{3^5}=\frac{-98}{81}\\
\frac{2^7\ -665}{3^6}=\frac{-179}{243}\\
\frac{2^7\ -64}{3^1}=\frac{64}{3}\\
\frac{2^7\ -67}{3^2}=\frac{61}{9}\\
\frac{2^7\ -70}{3^2}=\frac{58}{9}\\
\frac{2^7\ -79}{3^3}=\frac{49}{27}\\
\frac{2^7\ -76}{3^2}=\frac{52}{9}\\
\frac{2^7\ -85}{3^3}=\frac{43}{27}\\
\frac{2^7\ -94}{3^3}=\frac{34}{27}\\
\frac{2^7\ -121}{3^4}=\frac{7}{81}\\
\frac{2^7\ -88}{3^2}=\frac{40}{9}\\
\frac{2^7\ -97}{3^3}=\frac{31}{27}\\
\frac{2^7\ -106}{3^3}=\frac{22}{27}\\
\frac{2^7\ -133}{3^4}=\frac{-5}{81}\\
\frac{2^7\ -124}{3^3}=\frac{4}{27}\\
\frac{2^7\ -151}{3^4}=\frac{-23}{81}\\
\frac{2^7\ -178}{3^4}=\frac{-50}{81}\\
\frac{2^7\ -259}{3^5}=\frac{-131}{243}\\
\frac{2^7\ -112}{3^2}=\frac{16}{9}\\
\frac{2^7\ -121}{3^3}=\frac{7}{27}\\
\frac{2^7\ -130}{3^3}=\frac{-2}{27}\\
\frac{2^7\ -157}{3^4}=\frac{-29}{81}\\
\frac{2^7\ -148}{3^3}=\frac{-20}{27}\\
\frac{2^7\ -175}{3^4}=\frac{-47}{81}\\
\frac{2^7\ -202}{3^4}=\frac{-74}{81}\\
\frac{2^7\ -283}{3^5}=\frac{-155}{243}\\
\frac{2^7\ -184}{3^3}=\frac{-56}{27}\\
\frac{2^7\ -211}{3^4}=\frac{-83}{81}\\
\frac{2^7\ -238}{3^4}=\frac{-110}{81}\\
\frac{2^7\ -319}{3^5}=\frac{-191}{243}\\
\frac{2^7\ -292}{3^4}=\frac{-164}{81}\\
\frac{2^7\ -373}{3^5}=\frac{-245}{243}\\
\frac{2^7\ -454}{3^5}=\frac{-326}{243}\\
\frac{2^7\ -697}{3^6}=\frac{-569}{729}\\
\frac{2^7\ -160}{3^2}=\frac{-32}{9}\\
\frac{2^7\ -169}{3^3}=\frac{-41}{27}\\
\frac{2^7\ -178}{3^3}=\frac{-50}{27}\\
\frac{2^7\ -205}{3^4}=\frac{-77}{81}\\
\frac{2^7\ -196}{3^3}=\frac{-68}{27}\\
\frac{2^7\ -223}{3^4}=\frac{-95}{81}\\
\frac{2^7\ -250}{3^4}=\frac{-122}{81}\\
\frac{2^7\ -331}{3^5}=\frac{-203}{243}\\
\frac{2^7\ -232}{3^3}=\frac{-104}{27}\\
\frac{2^7\ -259}{3^4}=\frac{-131}{81}\\
\frac{2^7\ -286}{3^4}=\frac{-158}{81}\\
\frac{2^7\ -367}{3^5}=\frac{-239}{243}\\
\frac{2^7\ -340}{3^4}=\frac{-212}{81}\\
\frac{2^7\ -421}{3^5}=\frac{-293}{243}\\
\frac{2^7\ -502}{3^5}=\frac{-374}{243}\\
\frac{2^7\ -745}{3^6}=\frac{-617}{729}\\
\frac{2^7\ -304}{3^3}=\frac{-176}{27}\\
\frac{2^7\ -331}{3^4}=\frac{-203}{81}\\
\frac{2^7\ -358}{3^4}=\frac{-230}{81}\\
\frac{2^7\ -439}{3^5}=\frac{-311}{243}\\
\frac{2^7\ -412}{3^4}=\frac{-284}{81}\\
\frac{2^7\ -493}{3^5}=\frac{-365}{243}\\
\frac{2^7\ -574}{3^5}=\frac{-446}{243}\\
\frac{2^7\ -817}{3^6}=\frac{-689}{729}\\
\frac{2^7\ -520}{3^4}=\frac{-392}{81}\\
\frac{2^7\ -601}{3^5}=\frac{-473}{243}\\
\frac{2^7\ -682}{3^5}=\frac{-554}{243}\\
\frac{2^7\ -925}{3^6}=\frac{-797}{729}\\
\frac{2^7\ -844}{3^5}=\frac{-716}{243}\\
\frac{2^7\ -1087}{3^6}=\frac{-959}{729}\\
\frac{2^7\ -1330}{3^6}=\frac{-1202}{729}\\
\frac{2^7\ -2059}{3^7}=\frac{-1931}{2187}\\
\end{Bmatrix}$$

### 2.5.3  Observations

  - Even and Odd generation Collatz sequences are disjoint
  - Generation N+2 solutions always include all Generation N solutions
  - Count(Generation N-1, Generation N) integer solutions ~ $2^\frac{N}{2}$
  - Small numbers can be generated by large N solutions

### 2.5.4 Maxima
  - The largest number that can and always will be newly introduced in each generation is $2^N$

### 2.5.5 Minima

  - I think it can be shown that the smallest number that can be introduced newly by a given generation is $\frac{N}{2}$, for instance generation 12 cannot introduce a number smaller than 6.  
  
Is there a way to turn this into a proof?  The Collatz conjecture would be false is there is a large N where preceding generations have failed to fill in all of the  $\frac{N}{2}$ values.

# 3. Contsraints on $n, m, c$

## 3.1 $ n \ \equiv \  N $

n is straightforwardly always the generation N

## 3.2 $ m $ ranges from $[ 0 ... N ]$

## 3.3 $ c $ -- TODO bring in Abacus work



# 4. Form-of Introductions

A cross generational way of viewing the $X[0]$ values introduced in each generation is to recognize them as introductions of the form of exponential series across generations.  Note these include the rational solutions as well as the integer solutions with the rational solutions possibly producing integer solutions in future generations if not the current.

# 4.1 Generation 0:  $\frac{2^n + 0}{3^0}$

The most obvious is generation 0's introduction of the form: $2^N$:

  - $\{1 ... 2^N\} \forall N \ \  $ -- every generation
    - $ 2^n\ \equiv\ 0\ mod\ 2\ for\ n > 0 $

# 4.1 Generation 1: 

Generation 1 introduces one new sequence:

  - $\frac{(2^n - 1)}{3^1} \Rightarrow \{(1), 5, 21, 85\}$ -- introduces new integers every other generation: $n = 2i + 1\ \forall\ i > 0$
    - $\frac{(2^{(2i+1)} - 1)}{3^1}\ \equiv\ 1\ mod\ 4$
    

# 4.2 Generation 2:

Generation 2 introduces two new sequences:

  -  $\frac{(2^n - 2)}{3^1} \Rightarrow \{(2), 10, 42\}$ -- introduces integers every other generation: $n = 2i + 1\ \forall\ i > 0$
    - $\frac{(2^n - 2)}{3^1}\ \equiv\ 2\ mod\ 8$
  - $\frac{(2^n - 5)}{3^2} \Rightarrow \{3, 227, 14563\}$ -- introduces integers every sixth generation: $n = 6i - 1\ \forall\ i > 0$
    - $\frac{(2^n - 5)}{3^2}\ \equiv\ 3\ mod\ 8$ 
    

# 4.2 Generation 3:

Generation 3 introduces $2^n - 2^{(n-1)} \ \equiv\ 4$ new sequences:

  -  $\frac{(2^n - 4)}{3^1} \Rightarrow \{(4), 20, 84, 340\}$ -- introduces integers every other generation: $n = 2i\ \forall\ i > 1$
    - $\frac{(2^n - 4)}{3^1}\ \equiv\ 4\ mod\ 16$
  - $\frac{(2^n - 7)}{3^2} \Rightarrow \{(1), 113, 7281\}$ -- introduces integers every sixth generation: $n = 6i + 1\ \forall\ i > 1$
    - $\frac{(2^n - 7)}{3^2}\ \equiv\ 1\ mod\ 16$ 
  - $\frac{(2^n - 10)}{3^2} \Rightarrow \{6, 454, 29126\}$ -- introduces integers every sixth generation: $n = 6i\ \forall\ i > 0$
    - $\frac{(2^n - 10)}{3^2}\ \equiv\ 6\ mod\ 16$ 
  - $\frac{(2^n - 7)}{3^2} \Rightarrow \{(3), 227, 14563\}$ -- introduces integers every eighteenth generation: $n = 18i - 6\ \forall\ i > 0$
    - $\frac{(2^n - 7)}{3^2}\ \equiv\ 7\ mod\ 16$ 


# Form-of Gaps

We can see that there are 2 types of gaps that are recusively partially filled by the form-of equations with each generation:

  - modulus gaps
  - exponential gaps
  
## Modulus Gaps

In order for the Collatz conjecture to be true, we have to know that the linear equations will generate all integers as $X[0]$.  Therefore any gap in modularity would show that the conjecture is false.

We can see that modulus 2 numbers can be recurively subdivided and we show the generation where we pick up a given modulus set.  Though remember that we do not get all values in each, just a sparse exponentially seperated set that meet the modulus criteria:

  - **0 mod 2** -- N=0
    - 0 mod 4
      - 0 mod 8
        - 0 mod 16
        - 8 mod 16
      - 4 mod 8
        - **4 mod 16** -- N=3
        - 12 mod 16
    - 2 mod 4
      - **2 mod 8** -- N=2
        - 2 mod 16
        - 10 mod 16
      - 6 mod 8
        - **6 mod 16** -- N=3
        - 14 mod 16
  - 1 mod 2
    - **1 mod 4** -- N=1
      - 1 mod 8
        - **1 mod 16** -- N=3
        - 9 mod 16
      - 5 mod 8
        - 5 mod 16
        - 13 mod 16
    - 3 mod 4
      - **3 mod 8** -- N=2
        - 3 mod 16
        - 11 mod 16
      - 7 mod 8
        - **7 mod 16** -- N=3
        - 15 mod 16

Because of the exponential spacing of the sequences, we have to introduce nested subsets of moduli fast enough to fill in the gaps introduced by the exponential spacing.

### The number that is never generated: $2^N-1\ as\ N\ \to\ \infty$

We can see above, and further recursion can make it more clear, that there is a sliver of the odd numbers $(2^N - 1)\ mod\ 2^N$ that is perpetually unaccounted for.  However this sliver vanishes to infinity as we recurse.

## Exponential Gaps

As noted, the sequences are exponential.  This is balanced by exponentially generating more distinct sequences (distinct with appropriately large n) with each generation as with each generation we introduce $2^N - 2^{N-1}$ new sequences.


# $\epsilon,\ \delta$ Thinking

Is there a way to push hard on the "Generation" axis, to create a situation where we will generate more values (even though sparse) than we are skipping?  Could this be combined with lower bound on packing to prove we will fill a given "box"?  

While we are generating solutions, looking for some number T, can we, by choosing an appropriate generation scheme guarantee that we will generate more distinct numbers than T?  For all T?  

# Association Matrix Thinking

Instead of generating a bunch of incomplete matrices related to the relationships between numbers, what if we instead did a number-to-generation matrix that was always complete for a given generation level?  


# Matrix Transform

There have to be transforms that give matrices that give the same $X[0]$ values, but in different orders.  